steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=slackbot --format='get(payload.data)' | tr '_-' '/+' | base64 -d >
env.yaml" ]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud functions deploy ActionHandler --runtime=go113 --trigger-http
--allow-unauthenticated --project=gcp-iam-slackbot --service-account=cloud-function-iam-slackbot@gcp-iam-slackbot.iam.gserviceaccount.com
--env-vars-file env.yaml" ]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud functions deploy SlashHandler --runtime=go113 --trigger-http
--allow-unauthenticated --project=gcp-iam-slackbot --service-account=cloud-function-iam-slackbot@gcp-iam-slackbot.iam.gserviceaccount.com
--env-vars-file env.yaml" ]
